# Generated by Django 5.0 on 2023-12-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraisecause',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cause_images'),
        ),
    ]
