# Generated by Django 5.0 on 2023-12-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_alter_fundraisecause_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
