# Generated by Django 5.0 on 2023-12-15 18:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_donation_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'verbose_name': 'Donation', 'verbose_name_plural': 'Donations'},
        ),
        migrations.AlterModelOptions(
            name='fundraisecause',
            options={'verbose_name': 'Fundraise Cause', 'verbose_name_plural': 'Fundraise Causes'},
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Enter the donation amount', max_digits=10),
        ),
        migrations.AlterField(
            model_name='donation',
            name='cause',
            field=models.ForeignKey(help_text='Select the cause you want to donate to', on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='donations.fundraisecause'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='email',
            field=models.EmailField(help_text='Enter your email', max_length=254),
        ),
        migrations.AlterField(
            model_name='donation',
            name='name',
            field=models.CharField(help_text='Enter your name', max_length=100),
        ),
        migrations.AlterField(
            model_name='donation',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Enter your phone number (optional)', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='fundraisecause',
            name='account_number',
            field=models.IntegerField(help_text='Enter the account number'),
        ),
        migrations.AlterField(
            model_name='fundraisecause',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Enter the current amount raised', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='fundraisecause',
            name='description',
            field=models.TextField(help_text='Enter a description of the cause'),
        ),
        migrations.AlterField(
            model_name='fundraisecause',
            name='goal',
            field=models.DecimalField(decimal_places=2, help_text='Enter the fundraising goal', max_digits=10),
        ),
        migrations.AlterField(
            model_name='fundraisecause',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image for the cause', null=True, upload_to='cause_images'),
        ),
        migrations.AlterField(
            model_name='fundraisecause',
            name='title',
            field=models.CharField(help_text='Enter the title of the cause', max_length=100),
        ),
    ]
