# Generated by Django 5.0 on 2023-12-16 06:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_alter_donation_options_alter_fundraisecause_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fundraisecause',
            options={},
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='donation',
            name='cause',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='donations.fundraisecause'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='donation',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='donation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='fundraisecause',
            name='account_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fundraisecause',
            name='current_amount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='fundraisecause',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fundraisecause',
            name='goal',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fundraisecause',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cause_images'),
        ),
        migrations.AlterField(
            model_name='fundraisecause',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
